[project]
name = "pipeline"
version = "0.1.0"
description = "Geoprocessing pipeline for the Chicago Transit Safety Explorer"
authors = [
    { email = "mattrmorlan@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pandas>=3.0.6",
    "requests>=2.34.2",
]

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
